---
- name: Install Nginx on Ubuntu latest version
  become: true
  ansible.builtin.apt:
    name: nginx
    state: latest
    update_cache: true
  when: nginx_ubuntu_version == ""

- name: Install Nginx on Ubuntu spesific version
  become: true
  ansible.builtin.apt:
    name: "nginx={{ nginx_ubuntu_version }}"
    state: present
    allow_downgrade: true
    update_cache: true
  when: nginx_ubuntu_version != ""

- name: Enabled autostart nginx
  become: true
  ansible.builtin.service:
    name: nginx
    enabled: true
