---
- name: nginx
  src: nginxinc.nginx
  version: "0.25.0"

- name: mysql
  src: geerlingguy.mysql
  version: "4.3.4"

- name: php
  src: geerlingguy.php
  version: "6.0.0"

- name: joola
  src: https://github.com/radamanth/joomla-ansible.git
  version: "1.0.4"

- name: initapps
  src: https://github.com/viasite-ansible/ansible-role-site.git
  version: "v3.11.0"
