---
- name: Create DIR for joomla
  become: true
  ansible.builtin.file:
    path: "{{ path_unzip }}"
    state: directory
    mode: '0755'

- name: Download joomla
  become: true
  ansible.builtin.get_url:
    url: "{{ joomla_url }}"
    dest: "{{ path_unzip }}/joomla.tar.gz"
    mode: '0755'

- name: Unarchive joomla
  become: true
  ansible.builtin.unarchive:
    src: "{{ path_unzip }}/joomla.tar.gz"
    dest: "{{ path_unzip }}"
    remote_src: true

- name: Delete joomla archive
  become: true
  ansible.builtin.file:
    path: "{{ path_unzip }}/joomla.tar.gz"
    state: absent

- name: Change owner files in joomla
  become: true
  ansible.builtin.file:
    path: "{{ path_unzip }}"
    owner: www-data
    group: www-data
    mode: '0755'
    recurse: true
