---
- name: Install python lib
  become: true
  ansible.builtin.apt:
    name: python3-mysqldb
    state: present

- name: Install Mysql
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  loop: "{{mysql_packages}}"

- name: started Mysql
  become: true
  ansible.builtin.service:
    name: mysql
    state: started


# Configure MySQL.
- ansible.builtin.include_tasks: users.yml
