---
- name: Install python lib
  become: true
  ansible.builtin.apt:
    name: python3-mysqldb
    state: present

- name: Install Mysql
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  loop: "{{mysql_packages}}"

    #- name: Set MySQL root password
    #become: true
  #community.mysql.mysql_user:
    #  name: root
    #host: localhost
    #password: "{{ mysql_root_password }}"
    #state: present

