---
# add mysql users for joomla
- name: Set users for mysql
  ansible.builtin.include_tasks: mysql_users.yml
# add mysql db for joomla
- name: Create and set db
  ansible.builtin.include_tasks: mysql_db.yml
# set joomla
- name: Sets for joomla
  ansible.builtin.include_tasks: joomla_set.yml
