---
# add mysql db for joomla
- ansible.builtin.include_tasks: mysql_db.yml
# add mysql users for joomla
- ansible.builtin.include_tasks: mysql_users.yml
# set joomla
- ansible.builtin.include_tasks: joomla_set.yml
