---
- name: Set MySQL root user
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
  #ignore_errors: yes

- name: MySQL users
  mysql_user:
    check_implicit_admin: true
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    host: "{{ item.host | default('localhost') }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ mysql_users }}"
