# start mysql
- name: Started Mysql
  become: true
  ansible.builtin.service:
    name: mysql
    state: started

# restart mysql
- name: Restarted Mysql
  ansible.builtin.service:
    name: mysql
    state: restarted

# start nginx
- name: Started Nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: started

# restart nginx
- name: Restart nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted

# restaart php
- name: Restart php
  become: true
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    state: restarted
