---
- name: Add PHP repository
  become: true
  ansible.builtin.apt_repository:
    repo: "ppa:ondrej/php"

- name: Install PHP on Ubuntu
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  loop: "{{ php_packages }}"
  when: php_version != ""

- name: Enabled autostart php
  become: true
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    enabled: true
