# php version
php_version: "8.1"

# necessary packages for role
php_packages:
  - php{{ php_version }}
  - php8.1-mysql
  - php8.1-fpm
  - php8.1-mbstring
  - php8.1-zip
  - php8.1-xml
  - php8.1-intl
  - php8.1-curl
  - php8.1-gd 
